version: 2
jobs:
  build:
   docker:
      - image: fadlyas/kernel_dockerfile:latest
   steps:
      - run:
          command: |
           git clone --quiet --depth=1 https://github.com/fadlyas07/kernel_xiaomi_citrus_sdm662 -b main kernel && cd kernel
           wget https://github.com/timangpopi1/repo/raw/master/build.sh
           export codename="citrus"
           export defconfig="vendor/citrus-perf_defconfig"
           chmod +x build.sh && bash ./build.sh $defconfig AoSpM
