version: 2
jobs:
  build:
   docker:
      - image: ubuntu:18.04
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install bc bison ca-certificates curl flex gcc \
           git libc6-dev libssl-dev make openssl python ssh wget zip
           git clone -q https://github.com/Nick89786/msmkernel-4.9 kernel && cd kernel
           git clone -q https://github.com/fadlyas07/anykernel-3 --depth=1
           export codename=rolex && export KBUILD_BUILD_TIMESTAMP=$(TZ=Asia/Jakarta date)
           git clone --depth=1 -q https://github.com/HANA-CI-Build-Project/proton-clang
           wget https://github.com/timangpopi1/repo/raw/gcc/build.sh
           chmod +x build.sh && bash ./build.sh rolex_defconfig
