version: 2
jobs:
  build:
   docker:
      - image: fadlyas/kernel_dockerfile:latest
   steps:
      - run:
          command: |
           # Install flex package for old aosp-dtc driver.
           apt-get -y install flex &> flex.txt
           msm_test=0
           export my_project="https://github.com/greenforce-project"
           if [[ ${msm_test} == 1 ]] ; then
               export target_branch="android-4.9-q"
               export target_repo="kernel_xiaomi_rova_sd425_4.9"
               git clone --quiet --depth=1 ${my_project}/${target_repo} -b ${target_branch} kernel && cd kernel
               wget https://github.com/timangpopi1/repo/raw/master/build.sh
               export codename="rova"
               export defconfig="rova_defconfig"
               chmod +x build.sh && bash ./build.sh $defconfig gcc
           elif [[ ${msm_test} == 2 ]] ; then
               export target_branch="4.9.r27"
               export target_repo="msm-4.9"
               git clone --quiet --depth=1 ${my_project}/${target_repo} -b ${target_branch} kernel && cd kernel
               wget https://github.com/timangpopi1/repo/raw/master/build.sh

               export codename="msm8937"
               export defconfig="msm8937-perf_defconfig"
               chmod +x build.sh && bash ./build.sh $defconfig gcc

               unset codename
               export codename="msm8953"
               unset defconfig
               export defconfig="msm8953-perf_defconfig"
               chmod +x build.sh && bash ./build.sh $defconfig gcc
           else
               export target_branch="lineage-18.0"
               export target_repo="kernel_xiaomi_whyred_sdm660"
               git clone --quiet --depth=1 ${my_project}/${target_repo} -b ${target_branch} kernel && cd kernel
               wget https://github.com/timangpopi1/repo/raw/master/build.sh
               export codename="whyred"
               export defconfig="vendor/whyred_defconfig"
               chmod +x build.sh && bash ./build.sh $defconfig clang
           fi
