version: 2
jobs:
  build:
   docker:
      - image: fadlyas/kernel_dockerfile:latest
   steps:
      - run:
          command: |
           git clone --quiet --depth=1 https://github.com/fadlyas07/kernel_xiaomi_lavender_sdm660 -b main kernel && cd kernel
           wget https://github.com/timangpopi1/repo/raw/master/build.sh
           export codename="lavender"
           export defconfig="lavender-perf_defconfig"
           chmod +x build.sh && bash ./build.sh AoSpM $defconfig
