version: 2
jobs:
  build:
   docker:
      - image: mhmmdfdlyas/dockerfile:k
   steps:
      - run:
          command: |
           TYPE=2
           ubuntu_codename=groovy
           wget https://apt.llvm.org/llvm-snapshot.gpg.key
           sudo apt-key add llvm-snapshot.gpg.key
           sudo add-apt-repository "deb http://apt.llvm.org/$ubuntu_codename/ llvm-toolchain-$ubuntu_codename main"
           sudo apt-get update
           sudo apt-get install -y clang llvm lld
           sudo apt-get install -y binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu binutils-arm-linux-gnueabi gcc-arm-linux-gnueabi
           sudo apt-get install -y libncurses-dev flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf
           if [[ $TYPE == 1 ]] ; then
               git clone --quiet --depth=1 https://github.com/fadlyas07/kernel_xiaomi_lavender_sdm660 -b main kernel
               cd kernel && wget https://github.com/timangpopi1/repo/raw/master/build.sh
               export codename="lavender" && export defconfig="lavender-perf_defconfig"
               chmod +x build.sh && bash ./build.sh $defconfig AoSpM
           elif [[ $TYPE == 2 ]] ; then
               git clone --depth=1 https://github.com/greenforce-project/kernel_xiaomi_citrus_sm6115 -b rvc kernel
               cd kernel && wget https://github.com/timangpopi1/repo/raw/master/build.sh
               export codename="juice" && export defconfig="vendor/juice-perf_defconfig"
               chmod +x build.sh && bash ./build.sh $defconfig GreenForce
           fi
