version: 2
jobs:
  build:
    docker:
      - image: fadlyas/kernel_dockerfile:latest
    steps:
      - run:
          command: |
            git clone --depth=1 https://github.com/timangpopi1/kernel_msm-4.9 kernel && cd kernel
            wget https://github.com/timangpopi1/repo/raw/master/build && bash build 'rolex_defconfig' 'rolex'
