version: 2
jobs:
  build:
   docker:
      - image: ubuntu:18.04
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install bc bison ca-certificates curl flex gcc \
           git libc6-dev libssl-dev make openssl python ssh wget zip
           git clone -q https://github.com/GreenForce-project-repositories/kernel_xiaomi_rova_sd425 --depth=1 -b lineage-eas kernel && cd kernel
           git clone -q https://github.com/fadlyas07/anykernel-3 --depth=1
           export codename=rolex && export KBUILD_BUILD_TIMESTAMP=$(TZ=Asia/Jakarta date)
           git clone --depth=1 -q https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 -b lineage-17.1 gcc
           git clone --depth=1 -q https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9 -b lineage-17.1 gcc32
           wget https://github.com/timangpopi1/repo/raw/master/build.sh
           chmod +x build.sh && bash ./build.sh rolex_defconfig
