version: 2
jobs:
  build:
    docker:
      - image: fadlyas/kernel_dockerfile:latest
    steps:
      - run:
          command: |
            git checkout && git clone --depth=1 https://github.com/Nick89786/android_kernel_xiaomi_msm8917 -b lineage-17.1 kernel && cd kernel
            bash build 'rolex defconfig'
