version: 2
jobs:
  build:
   docker:
      - image: ubuntu:18.04
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install clang llvm lld binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu binutils-arm-linux-gnueabi gcc-arm-linux-gnueabi \
           bc bison ca-certificates curl flex gcc git libc6-dev libssl-dev make openssl python ssh sudo wget zip libncurses-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf
           TZ=Asia/Jakarta && sudo ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
           apt-get -y install tzdata
           TYPE=2
           if [[ $TYPE == 1 ]] ; then
               git clone --quiet --depth=1 https://github.com/fadlyas07/kernel_xiaomi_lavender_sdm660 -b main kernel
               cd kernel && wget https://github.com/timangpopi1/repo/raw/master/build.sh
               export codename="lavender" && export defconfig="lavender-perf_defconfig"
               chmod +x build.sh && bash ./build.sh $defconfig AoSpM
           elif [[ $TYPE == 2 ]] ; then
               git clone --quiet --depth=1 https://github.com/kdrag0n/proton_kernel_redbull -b master kernel
               cd kernel && wget https://github.com/timangpopi1/repo/raw/master/build.sh
               export codename="redbull" && export defconfig="redbull_defconfig"
               chmod +x build.sh && bash ./build.sh $defconfig AoSpM
           fi
