version: 2
jobs:
  build:
   docker:
      - image: ubuntu:latest
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install bc bison ca-certificates curl flex gcc \
           git libc6-dev libssl-dev make openssl python ssh wget zip >> ubuntu.log
           msm_test=0
           export my_project="https://github.com/greenforce-project"
           if [[ ${msm_test} == 1 ]] ; then
               export target_branch="main"
               export target_repo="kernel_xiaomi_rova_sd425_4.9"
               git clone --quiet --depth=1 ${my_project}/${target_repo} -b ${target_branch} kernel && cd kernel
               wget https://github.com/timangpopi1/repo/raw/master/build.sh

               export codename="rolex"
               export defconfig="rolex_defconfig"
               chmod +x build.sh && bash ./build.sh $defconfig gcc

               unset codename
               export codename="riva"
               unset defconfig
               export defconfig="riva_defconfig"
               chmod +x build.sh && bash ./build.sh $defconfig gcc
           else
               export target_branch="lineage-17.1"
               export target_repo="kernel_xiaomi_whyred_sdm660"
               git clone --quiet --depth=1 ${my_project}/${target_repo} -b ${target_branch} kernel && cd kernel
               wget https://github.com/timangpopi1/repo/raw/master/build.sh

               export codename="whyred-(newcam)"
               export defconfig="whyred_defconfig"
               chmod +x build.sh && bash ./build.sh $defconfig clang

               unset codename
               export codename="whyred-(oldcam)"
               unset defconfig
               export defconfig="whyred_defconfig"
               sed -i 's/CONFIG_MACH_XIAOMI_NEW_CAMERA=y/# CONFIG_MACH_XIAOMI_NEW_CAMERA is not set/g' arch/arm64/configs/whyred_defconfig
               chmod +x build.sh && bash ./build.sh $defconfig clang
           fi
