version: 2
jobs:
  build:
   docker:
      - image: ubuntu:18.04
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install bc bison ca-certificates curl flex gcc \
           git libc6-dev libssl-dev make openssl python ssh wget zip
           git clone -q https://github.com/GreenForce-project-repositories/kernel_xiaomi_whyred_sdm660 --depth=1 -b lineage-eas kernel && cd kernel
           git clone -q https://github.com/fadlyas07/anykernel-3 --depth=1
           export codename=whyred-oldcam && export KBUILD_BUILD_TIMESTAMP=$(TZ=Asia/Jakarta date)
           wget https://github.com/timangpopi1/repo/raw/sdm/build.sh
           chmod +x build.sh && bash ./build.sh whyred_defconfig
