version: 2
jobs:
  build:
   docker:
      - image: fadlyas/kernel_dockerfile:latest
   steps:
      - run:
          command: |
           apt-get -y install flex tar &> nou.txt
           msm_test=3
           export my_project="https://github.com/greenforce-project"
           if [[ ${msm_test} == 1 ]] ; then
               export target_branch="android-4.9-q"
               export target_repo="kernel_xiaomi_rova_sd425_4.9"
               git clone --quiet --depth=1 ${my_project}/${target_repo} -b ${target_branch} kernel && cd kernel
               wget https://github.com/timangpopi1/repo/raw/master/build.sh
               export codename="rova"
               export defconfig="rova_defconfig"
               chmod +x build.sh && bash ./build.sh $defconfig gcc
           elif [[ ${msm_test} == 2 ]] ; then
               export target_branch="4.9.r27"
               export target_repo="msm-4.9"
               git clone --quiet --depth=1 ${my_project}/${target_repo} -b ${target_branch} kernel && cd kernel
               wget https://github.com/timangpopi1/repo/raw/master/build.sh
               export codename="msm8937"
               export defconfig="msm8937-perf_defconfig"
               chmod +x build.sh && bash ./build.sh $defconfig gcc
               unset codename
               export codename="msm8953"
               unset defconfig
               export defconfig="msm8953-perf_defconfig"
               chmod +x build.sh && bash ./build.sh $defconfig gcc
           elif [[ ${msm_test} == 3 ]] ; then
               export target_branch="ruby-4.19"
               export target_repo="https://github.com/aospa-whyred/android_kernel_xiaomi_whyred-4.19"
               git clone --quiet --depth=1 ${target_repo} -b ${target_branch} kernel && cd kernel
               wget https://github.com/timangpopi1/repo/raw/master/build.sh
               export codename="whyred-4.19"
               export defconfig="vendor/whyred_defconfig"
               chmod +x build.sh && bash ./build.sh $defconfig clang
           elif [[ ${msm_test} == 4 ]] ; then
               export target_branch="lineage-17.1"
               export target_repo="kernel_xiaomi_whyred_sdm660"
               git clone --quiet --depth=1 ${my_project}/${target_repo} -b ${target_branch} kernel && cd kernel
               wget https://github.com/timangpopi1/repo/raw/master/build.sh
               export codename="whyred-(newcam)"
               export defconfig="whyred_defconfig"
               chmod +x build.sh && bash ./build.sh $defconfig gcc-elf
               unset codename
               export codename="whyred-(oldcam)"
               unset defconfig
               export defconfig="whyred_defconfig"
               sed -i 's/CONFIG_MACH_XIAOMI_NEW_CAMERA=y/# CONFIG_MACH_XIAOMI_NEW_CAMERA is not set/g' arch/arm64/configs/whyred_defconfig
               chmod +x build.sh && bash ./build.sh $defconfig gcc-elf
           fi
