version: 2
jobs:
  build:
   docker:
      - image: ubuntu:18.04
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install bc bison ca-certificates curl flex gcc \
           git libc6-dev libssl-dev make openssl python ssh wget zip
           git clone https://github.com/fadlyas07/android_kernel_xiaomi_sdm660 --depth=1 -b Q kernel && cd kernel
           sed -i 's/CONFIG_XIAOMI_NEW_CAMERA_BLOBS=y/# CONFIG_XIAOMI_NEW_CAMERA_BLOBS is not set/g' arch/arm64/configs/whyred_defconfig
           git clone https://github.com/fadlyas07/anykernel-3 --depth=1
           export codename=whyred-oldcam
           git clone --depth=1 https://github.com/chips-project/aarch64-elf gcc
           git clone --depth=1 https://github.com/chips-project/arm-eabi gcc32
           wget https://github.com/timangpopi1/repo/raw/master/build.sh
           chmod +x build.sh && bash ./build.sh whyred_defconfig
           echo "lol"
