version: 2
jobs:
  build:
   docker:
      - image: z4nyx/docker:latest
   steps:
      - run:
          command: |
           TYPE=2
           if [[ $TYPE == 1 ]] ; then
               git clone --quiet --depth=1 https://github.com/fadlyas07/kernel_xiaomi_lavender_sdm660 -b main kernel
               cd kernel && wget https://github.com/timangpopi1/repo/raw/master/build.sh
               export codename="lavender" && export defconfig="lavender-perf_defconfig"
               chmod +x build.sh && bash ./build.sh $defconfig AoSpM
           elif [[ $TYPE == 2 ]] ; then
               git clone --quiet --depth=1 https://github.com/fadlyas07/kernel_xiaomi_juice_sm6115 -b ruby kernel
               cd kernel && wget https://github.com/timangpopi1/repo/raw/master/build.sh
               export codename="citrus" && export defconfig="vendor/citrus_defconfig"
               cd arch/arm64/configs/vendor/ && rm -rf citrus-perf_defconfig
               wget -O citrus_defconfig https://github.com/MoonBase-Project/MSM-4.19-MiBengal/raw/9082b90490d107e909e492df4295cdbc3d3e44ef/arch/arm64/configs/vendor/mibengal_defconfig
               cd ../../../../
               chmod +x build.sh && bash ./build.sh $defconfig AoSpM
           fi
