version: 2
jobs:
  build:
   docker:
      - image: ubuntu:latest
   steps:
      - run:
          command: |
           apt-get update -qq && apt-get upgrade -y && apt-get install --no-install-recommends -y install glibc-doc \
           bc bison ca-certificates curl flex gcc git libc6-dev libssl-dev make openssl python ssh sudo wget zip
           TZ=Asia/Jakarta && sudo ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
           apt-get -y install tzdata
           TYPE=2
           if [[ $TYPE == 1 ]] ; then
               git clone --quiet --depth=1 https://github.com/fadlyas07/kernel_xiaomi_lavender_sdm660 -b main kernel
               cd kernel && wget https://github.com/timangpopi1/repo/raw/master/build.sh
               export codename="lavender" && export defconfig="lavender-perf_defconfig"
               chmod +x build.sh && bash ./build.sh $defconfig AoSpM
           elif [[ $TYPE == 2 ]] ; then
               git clone -j64 --depth=1 https://github.com/greenforce-project/kernel_xiaomi_citrus_sm6115 -b lineage-18.1 kernel
               cd kernel && wget https://github.com/timangpopi1/repo/raw/master/build.sh
               export codename="juice" && export defconfig="vendor/juice-perf_defconfig"
               chmod +x build.sh && bash ./build.sh $defconfig GreenForce
           fi
