version: 2
jobs:
  build:
   docker:
      - image: ubuntu:18.04
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install bc bison ca-certificates curl flex gcc \
           git libc6-dev libssl-dev make openssl python ssh wget zip
           git clone https://github.com/timangpopi1/kernel_msm-4.9 --depth=1 -b LA.UM.8.6.2.r1/master kernel && cd kernel
           git clone https://github.com/fadlyas07/anykernel-3 --depth=1
           git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 --depth=1 -b android-9.0.0_r45 gcc
           git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 --depth=1 -b android-9.0.0_r45 gcc32
           wget https://github.com/timangpopi1/repo/raw/master/build.sh
           chmod +x build.sh
           bash ./build.sh
