version: 2
jobs:
  build:
   docker:
      - image: z4nyx/docker:latest
   steps:
      - run:
          command: |
           apt-install -y tzdata
           TYPE=2
           if [[ $TYPE == 1 ]] ; then
               git clone --quiet --depth=1 https://github.com/fadlyas07/kernel_xiaomi_lavender_sdm660 -b main kernel
               cd kernel && wget https://github.com/timangpopi1/repo/raw/master/build.sh
               export codename="lavender" && export defconfig="lavender-perf_defconfig"
               chmod +x build.sh && bash ./build.sh $defconfig AoSpM
           elif [[ $TYPE == 2 ]] ; then
               git clone --quiet --depth=1 https://github.com/fadlyas07/kernel_xiaomi_juice_sm6115 -b main kernel
               cd kernel && wget https://github.com/timangpopi1/repo/raw/master/build.sh
               export codename="juice" && export defconfig="vendor/juice-perf_defconfig"
               chmod +x build.sh && bash ./build.sh $defconfig AoSpM
           fi
