version: 2
jobs:
  build:
   docker:
      - image: ubuntu:18.04
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install bc bison ca-certificates curl flex gcc \
           git libc6-dev libssl-dev make openssl python ssh wget zip
           git clone -q https://github.com/fadlyas07/android_kernel_xiaomi_sdm660 --depth=1 -b Q kernel && cd kernel
           sed -i 's/CONFIG_XIAOMI_NEW_CAMERA_BLOBS=y/# CONFIG_XIAOMI_NEW_CAMERA_BLOBS is not set/g' arch/arm64/configs/whyred_defconfig
           git clone -q https://github.com/fadlyas07/anykernel-3 --depth=1
           export codename=whyred-oldcam
           git clone -q https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 --depth=1 -b android-9.0.0_r59 gcc
           git clone -q https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 --depth=1 -b android-9.0.0_r59 gcc32
           wget https://github.com/timangpopi1/repo/raw/master/build.sh
           chmod +x build.sh && bash ./build.sh whyred_defconfig
